In [61]:
using FourierFlows
include("../ExactRadialSpectrum.jl")

set_top_clip_weights (generic function with 1 method)

In [62]:
using BenchmarkTools

In [63]:
grid = TwoDGrid(;nx=32, Lx=2π)

radii, weights = create_radialspectrum_weights(grid, 1, 1)

(1.0:1.0:17.0, SparseMatrixCSC[sparse([1, 2, 1, 2, 1, 2], [1, 1, 2, 2, 32, 32], [1.0, 0.9132229549810363, 0.45661147749051817, 0.1575733718138602, 0.45661147749051817, 0.1575733718138602], 17, 32), sparse([2, 3, 1, 2, 3, 1, 2, 1, 2, 1, 2, 3], [1, 1, 2, 2, 2, 3, 3, 31, 31, 32, 32, 32], [1.0867770450189638, 0.9579337142403377, 0.5433885225094819, 1.8123649194552873, 0.4276566508350509, 0.47896685712016884, 0.4276566508350509, 0.47896685712016884, 0.4276566508350509, 0.5433885225094819, 1.8123649194552873, 0.4276566508350509], 17, 32), sparse([3, 4, 2, 3, 4, 1, 2, 3, 4, 1  …  1, 2, 3, 1, 2, 3, 4, 2, 3, 4], [1, 1, 2, 2, 2, 3, 3, 3, 3, 4  …  30, 30, 30, 31, 31, 31, 31, 32, 32, 32], [1.0420662857596623, 0.972105317504216, 0.030061708730852565, 1.572343349164949, 0.623450638662556, 0.5210331428798312, 1.572343349164949, 1.3863891348138517, 0.01588560575544509, 0.486052658752108  …  0.486052658752108, 0.623450638662556, 0.01588560575544509, 0.5210331428798312, 1.572343349164949, 1.386389134813

In [66]:
weights[1]

17×32 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
⎡⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⎤
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎦

In [69]:
#test_data = grid.Krsq
test_data = ones(grid.nkr, grid.nl)
oneDspectrum = radialspectrum(test_data, weights)
diff(oneDspectrum)

16-element Vector{Float64}:
   6.283185307179586
   6.2831853071795845
   6.283185307179595
   6.283185307179583
   6.283185307179579
   6.2831853071796
   6.283185307179586
   6.283185307179593
   6.283185307179544
   6.283185307179643
   6.283185307179551
   6.283185307179593
   6.283185307179551
   6.283185307179664
   0.9749221555840251
 -16.758052204824736

In [60]:
grid.l

1×32 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0  5.0  6.0  …  -6.0  -5.0  -4.0  -3.0  -2.0  -1.0

In [55]:
using SparseArrays

In [64]:
a = Vector{SparseMatrixCSC}(undef, 10)

10-element Vector{SparseMatrixCSC}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef