In [1]:
using FourierFlows
include("../ExactRadialSpectrum.jl")

set_top_clip_weights (generic function with 1 method)

In [2]:
using BenchmarkTools

In [3]:
grid = TwoDGrid(;nx=32, Lx=2π)

radii, weights = create_radialspectrum_weights(grid, 1, 1)

LoadError: MethodError: no method matching create_radialspectrum_weights(::TwoDGrid{Float64, Matrix{Float64}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, FFTW.cFFTWPlan{ComplexF64, -1, false, 2, Tuple{Int64, Int64}}, FFTW.rFFTWPlan{Float64, -1, false, 2, Tuple{Int64, Int64}}, UnitRange{Int64}, CPU}, ::Int64, ::Int64)

Closest candidates are:
  create_radialspectrum_weights(::Any, ::Any)
   @ Main ~/JuliaRaytracingSW/utils/ExactRadialSpectrum.jl:4
  create_radialspectrum_weights(::Any)
   @ Main ~/JuliaRaytracingSW/utils/ExactRadialSpectrum.jl:4


In [66]:
weights[1]

17×32 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
⎡⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⎤
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎦

In [69]:
#test_data = grid.Krsq
test_data = ones(grid.nkr, grid.nl)
oneDspectrum = radialspectrum(test_data, weights)
diff(oneDspectrum)

16-element Vector{Float64}:
   6.283185307179586
   6.2831853071795845
   6.283185307179595
   6.283185307179583
   6.283185307179579
   6.2831853071796
   6.283185307179586
   6.283185307179593
   6.283185307179544
   6.283185307179643
   6.283185307179551
   6.283185307179593
   6.283185307179551
   6.283185307179664
   0.9749221555840251
 -16.758052204824736

In [60]:
grid.l

1×32 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0  5.0  6.0  …  -6.0  -5.0  -4.0  -3.0  -2.0  -1.0

In [55]:
using SparseArrays

In [64]:
a = Vector{SparseMatrixCSC}(undef, 10)

10-element Vector{SparseMatrixCSC}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef